# 建立一个名为CI的工作流
name: CI

# 监听 master上的push事件
on:
  push:
    branches: [master]

# 开始任务
jobs:
  # 建立一个名为 build 的job
  build:
    # 在最新的乌班图环境进行工作
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # 开始设置构建步骤
    steps:
      # 这是github官方的一个action，用于clone该仓库的源码到工作流中，
      - uses: actions/checkout@v2
       # 命名这个步骤为构建Build
      - name: Build
      #运行安装和打包任务
        run: npm install && npm run build
      
      # 命名这个任务为发布Deploy
      - name: Deploy
        uses: cross-the-world/scp-pipeline@master
        env:
          ELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.TG_HOST }}
          user: ${{ secrets.TG_USER }}
          pass: ${{ secrets.TG_PASS }}
          connect_timeout: 10s
          local: './dist/*'
          remote: /usr/share/nginx/html
